# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Enter a book's natural language (e.g. English, French, Japanese etc.)", max_length=200)),
            ],
        ),
    ]
